<a href="https://colab.research.google.com/github/MIKRAMS1984/Creating-ML-model-using-Linear-Regression/blob/main/Check_array_elements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
W=100
weights = np.random.randint(-100,100,(1,12))
#weights=np.arange(0.0, 10, 0.5)
weights, weights.dtype, weights.shape, W
#weights, weights.shape, weights.dtype

(array([[ 37,  25, -71,  79,  60, -80,  39,   3,  95, -92,   4, -59]]),
 dtype('int64'),
 (1, 12),
 100)

In [ ]:
from sys import exit

is_all_positive_integers = np.all((weights > 0))
if is_all_positive_integers:
    print('Weights Array contains only positive integers.')
else:
  print("Enter positive values for weights.")
exit
print("ikram")

Enter positive values for weights.
ikram


In [ ]:
W = 3
assert(W > 0)

In [ ]:
weights, W = np.floor(weights), np.floor(W)
weights, W

(array([[ 37.,  25., -71.,  79.,  60., -80.,  39.,   3.,  95., -92.,   4.,
         -59.]]), 3.0)

In [ ]:
b = np.floor(a)
b

In [ ]:
#import math.floor
#if (weights < 0) or (W < 0):
np.logical_or(weights < 0, W < 0)
print("enter positive numbers.")
W = math.floor(W)
def myfun():
  np.logical_or(weights < 0, W < 0)
  return math.floor(W)
#f2 = np.vectorize(weights)
weights = np.vectorize(myfun)
#weights = math.floor(f2)
  

In [ ]:
arr = np.array([4, 1, 2, 3, 4, 5])
arr

array([4, 1, 2, 3, 4, 5])

In [ ]:
is_all_positive_integers = np.all((arr > 0))
if is_all_positive_integers:
    print('Weights Array contains only positive integers.')
else:
    print('Array has non-positive_integers too')

Array has non-positive_integers too


In [ ]:
a=np.arange(0.0, 10, 0.5)
a, a.dtype, a.shape


(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
        6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]), dtype('float64'), (20,))